services:
  hl7_app:
    build:
      context: .         # la raíz, donde está el Dockerfile
      dockerfile: Dockerfile
    container_name: hl7_app
    ports:
      - "8000:8000"      # expone Gunicorn
    volumes:
      - ./config:/usr/src/app/config
      - ./certs/client.crt:/usr/src/app/certs/client.crt:ro
      - ./certs/client.key:/usr/src/app/certs/client.key:ro
      - ./certs/ca.crt:/usr/src/app/certs/ca.crt:ro
      - ./logs:/usr/src/app/logs
    networks:
      - hl7net

  nginx:
    image: nginx:stable-alpine
    container_name: hl7_nginx
    depends_on:
      - hl7_app
    ports:
      - "443:443"        # HTTPS + mTLS
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./certs/server.crt:/etc/nginx/certs/server.crt:ro
      - ./certs/server.key:/etc/nginx/certs/server.key:ro
      - ./certs/ca.crt:/etc/nginx/certs/ca.crt:ro
    networks:
      - hl7net

networks:
  hl7net:
    driver: bridge

